name: AMS Setup
description: Setup AMS enviroment variables
author: a3.services
branding:
  icon: settings
  color: purple
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git fetch --unshallow || git fetch
        echo "AMS_REVISION=$(git describe --tags)" >> $GITHUB_ENV
